from django.urls import path
from ops import views

urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.maintainAccountView, name='maintainAccountView'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('home', views.home, name='home'),
    path('api/userlogin', views.proccessLogin, name='userlogin'), 
    path('account/create', views.createAccountView, name='createAccountView'), 
    path('account/maintain/<str:client_id>', views.maintainAccountView, name='maintainAccountView'), 
    path('account/creating', views.createAccount, name='createAccount'), 
    path('business/getBusinessTypes', views.getBusinessTypes, name='getBusinessTypes'), 
    path('area/getAreaNames', views.getAreaNames, name='getAreaNames'), 
    path('industry/getIndustries', views.getIndustries, name='getIndustries'), 
    path('country/getCountries', views.getCountries, name='getCountries'),
    path('payment/getPaymentOptions', views.getPaymentOptions, name='getPaymentOptions'), 
    path('area/getAreaNames/<str:area_code>', views.getAreaNames, name='getAreaNames'), 
    path('linetype/getLineTypes', views.getLineTypes, name='getLineTypes'), 
    path('staff/getAllStaffs', views.getAllStaffs, name='getAllStaffs'), 
    path('positions/getCompanyPositions', views.getCompanyPositions, name='getCompanyPositions'), 
    path('api/searchClient', views.searchClient, name='searchClient'), 
    path('getcreateAccountPage', views.getcreateAccountPage, name='getcreateAccountPage'), 
    path('getInvoices/<str:clientId>', views.getInvoices, name='getInvoices'), 
    path('client/getCredits/<str:clientId>', views.getCredits, name='getCredits'), 
    path('client/getOneoffinvoices/<str:clientId>', views.getOneoffinvoices, name='getOneoffinvoices'),
    path('client/getOneOffCharges/<str:clientId>', views.getOneOffCharges, name='getOneOffCharges'),
    path('client/getContacts/<str:clientId>', views.getContacts, name='getContacts'), 
    path('client/getClientPhones/<str:clientId>', views.getClientPhones, name='getClientPhones'), 
    path('client/getAccountSummary/<str:clientId>', views.getAccountSummary, name='getAccountSummary'), 
    path('client/createContact/<str:clientId>', views.createContact, name='createContact'), 
    path('client/createPhone/<str:clientId>', views.createPhone, name='createPhone'), 
    path('client/createTollfree/<str:clientId>', views.createTollfree, name='createTollfree'), 
    path('client/createStandingCharges/<str:clientId>', views.createStandingCharges, name='createStandingCharges'), 
    path('client/createOneOffCharges/<str:clientId>', views.createOneOffCharges, name='createOneOffCharges'), 
    path('client/getPayments/<str:clientId>', views.getPayments, name='getPayments'),
    path('client/getMobiles/<str:clientId>', views.getMobiles, name='getMobiles'),
    path('client/getTollFree/<str:clientId>', views.getTollFree, name='getTollFree'), 
    path('client/getStandingCharges/<str:clientId>', views.getStandingCharges, name='getStandingCharges'),
    path('client/getWhitelabel/<str:clientId>', views.getWhitelabel, name='getWhitelabel'),
    path('client/createWhiteLabel/<str:clientId>', views.createWhiteLabel, name='createWhiteLabel'),
    path('client/editClient', views.createAccount),
    path('plans/getMobilePlans', views.getMobilePlans, name='getMobilePlans'), 
    path('plans/getMobileGroupPlans', views.getMobileGroupPlans, name='getMobileGroupPlans'), 
    path('partner/maintain/<str:partner_id>', views.maintainPartnerView, name='maintainPartnerView'), 
    path('partner/edit', views.editPartner, name='editPartner'), 
    path('partner/searchPartner', views.searchPartner, name='searchPartner'), 
    path('partner/getClients/<str:partner_id>', views.getClients),
    path('providers/getServiceProviders', views.getServiceProviders, name='getServiceProviders'),
    path('staff/getAllStaffs', views.getAllStaffs, name='getAllStaffs'), 

    
]